function createfigure1(zdata1,i)
%CREATEFIGURE1(ZDATA1,ZDATA2,ZDATA3,ZDATA4,ZDATA5,ZDATA6)
%  ZDATA1:  contour z
%  ZDATA2:  contour z
%  ZDATA3:  contour z
%  ZDATA4:  contour z
%  ZDATA5:  contour z
%  ZDATA6:  contour z

%  Auto-generated by MATLAB on 21-Feb-2011 14:20:31

zdata1=rot90(zdata1);

% Create figure
scrsz = get(0,'ScreenSize');
figure1 = figure('PaperType','a4letter','PaperSize',[20.98 29.68],'Position',[1 1 scrsz(3)/2.9 scrsz(4)/2]);

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.045 0.05 0.8 0.9],...
    'PlotBoxAspectRatio',[1 1 1],...
    'Layer','top');
% Uncomment the following line to preserve the X-limits of the axes
xlim([1 64]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim([1 64]);
box('on');
hold('all');

% Create pcolor plot

h=imagesc(zdata1);
set(h,'alphadata',~isnan(zdata1),'Parent',axes1);

% contour(zdata1,min(min(zdata1)):max(max(zdata1))/40:max(max(zdata1)),'LineStyle','none','LineColor',[0 0 0],...
%     'Fill','on',...
%     'Parent',axes1);

% Create title
%title({'Sensor 1'},'FontSize',14);

% Create colorbar
t=colorbar('peer',axes1);
%set(get(t,'ylabel'),'String', 'Void fraction [%]','FontSize',14);
set(axes1,'Position',[0.045 0.05 0.8 0.9]);

if i==1
set(get(t,'ylabel'),'String', 'x velocity component [m/s]','FontSize',14);
caxis([-0.5 0.5])
title('x velocity');
end

if i==2
set(get(t,'ylabel'),'String', 'y velocity component [m/s]','FontSize',14);
caxis([-0.5 0.5])
title('y velocity');
end

if i==3
set(get(t,'ylabel'),'String', 'z velocity component [m/s]','FontSize',14);
caxis([0.5 1.5])
title('z velocity');
end


if i==4
set(get(t,'ylabel'),'String', 'lateral velocity component [m/s]','FontSize',14);
caxis([0 0.5])
title('lateral velocity');
end

if i==5
set(get(t,'ylabel'),'String', 'total velocity [m/s]','FontSize',14);
caxis([0.5 1.5])
title('total velocity');
end
% Resize the axes in order to prevent it from shrinking.






